### DISCUSSION TITLE
[Question] Multiple JobRunr dashboards in a kubernetes cluster

### DISCUSSION THREAD

**Discussion by n-kulic** [jobrunr/jobrunr#1051] [General]
When running multiple Spring Boot instances in a Kubernetes cluster, each instance starts a JobRunr dashboard as that's what's defined in `application.yml` configuration:
```yml
org:
  jobrunr:
    dashboard:
      enabled: true
    background-job-server:
      enabled: true
```

What strategies or best practices can be applied to ensure only one instance of the JobRunr dashboard is running to avoid redundancy and resource wastage? Looking for recommendations or configurations to centralize the JobRunr dashboard while keeping the job processing distributed across multiple instances.
