### DISCUSSION TITLE
I would like the jobrunner dashboard to run on the same port as spring, is this possible?

### DISCUSSION THREAD

**Discussion by wesleyjesus-dev** [jobrunr/jobrunr#241] [Q&A] [answered]
I would like the jobrunner dashboard to run on the same port as spring, is this possible?

**Comment by rdehuyss** [comment, marked as answer]
~~I'm afraid not - it starts its own webserver.~~

~~Reason for this is that it is agnostic to which framework (Spring, Micronaut, Quarkus, ...) you use.~~

This is now possible out-of-the-box with JobRunr Pro.

**Reply by wesleyjesus-dev** [reply]
Understand. Thanks for explanation

**Comment by rdehuyss** [comment]
See also #249.

**Reply by wesleyjesus-dev** [reply]
Thanks! this helped. i implemented! It worked

**Reply by wesleyjesus-dev** [reply]
At the my case, the jobrunr running in 8080 port, so, i configuration like this

application.yaml
```
zuul:
  routes:
    dashboard:
      path: /dashboard/**
      url: http://localhost:8080/dashboard
    api:
      path: /api/**
      url: http://localhost:8080/api
    sse:
      path: /sse/**
      url: http://localhost:8080/sse
```

**Reply by hugo-lorenzo-mato** [reply]
Hi! I was looking for some information on this. In my case I am deploying Spring Boot applications on app webs in Azure (app services). And as far as I know I can't expose more ports than 443. My tomcat runs on 8080.

Any alternative? I could query the API for some basic information, but the interface was interesting for non-technical roles to perform some checks.

Right now I am not planning to migrate to more flexible solutions like ACI or Kubernetes.

I was thinking of deploying another instance that exposes the dashboard, but I see it as too much for my intended use.

I also thought about using Spring Cloud and doing a reverse proxy. But I make use of Spring MVC and they are incompatible. I leave the solution in case anyone can use it:

```yaml
spring:
  cloud:
    gateway:
      routes:
        - id: dashboard-route
          uri: http://localhost:8000
          predicates:
            - Path=/dashboard/**
          filters:
            - RewritePath=/dashboard/(?<remaining>.*), /$${remaining}
        - id: api-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<remaining>.*), /$/$remaining.
        - id: sse-route
          uri: http://localhost:8000
          predicates:
            - Path=/sse/**
          filters:
            - RewritePath=/sse/(?<remaining>.*), /$$remaining}
```

Any suggestions? I like what I saw of the solution, but one of the points I valued is the visualization of the executions.

Thanks for the great work.
