### DISCUSSION TITLE
database.skip-create on spring-boot + liquibase breaking the Application

### DISCUSSION THREAD

**Discussion by laguiar** [jobrunr/jobrunr#246] [Q&A]
Hi folks,
No sure if it might be a bug or is something missing in terms of configuration.

after adding to application.yaml:
```
org:
  jobrunr:
    database:
      skip-create: true
```

and providing a proper liquibase migration to create all necessary JobRunr tables, the Application don’t start anymore:
> Not all required tables are available by JobRunr

It seems that JobRunr tries to verify the existence of the DB tables before Liquibase actually have ran, causing the exception and killing the application.

Any hints or suggestion on this?
cheers.

ps:
spring-boot 2.5.6
jobRunr 4.0.1

**Comment by rdehuyss** [comment]
Really strange this all changed recently by the 4.0 release. I still cannot pinpoint why JobRunr now is running before the database migration tools.

**Reply by laguiar** [reply]
@rdehuyss let me know if I can try to help somehow 😉

**Reply by rdehuyss** [reply]
Well, I was thinking of something like `skip-create-and-validation` but I'm quite busy the coming weeks.

If you could create a PR that could definitely help.

**Reply by laguiar** [reply]
@rdehuyss as an additional configuration option?

I will try to at least draft something.

**Reply by tedliang** [reply]
#247 should fix this issue

**Reply by bcode2** [reply]
Still  getting the same error    Table 'TASK_EXECUTION, TASK_LOCK, etc ' already exists... . the option skip_create:  is not suppose to  skip table creation? . Using the last version 5.0.1. with Spring boot. Any idea?
```
org:
  jobrunr:
    database:
      table-prefix: ''      
      datasource: jobRunrdataSource   
      skip_create: true
```
