### DISCUSSION TITLE
Configuring job filters sing application.yaml

### DISCUSSION THREAD

**Discussion by igorg-il** [jobrunr/jobrunr#415] [Q&A]
I am trying to configure job filters JobClientFilter/JobServerFilter.
Is there a way to do it using application.yaml like org.jobrunr.background-job-server.enabled ?

Tried also by code - but adding filters to configuration in code JobRunr.configure().withJobFilter is ignored

Thank you

```
 @Bean
    public JobRunrConfigurationResult jobRunrConfigurationResult(MongoDBStorageProvider mongoDBStorageProvider) {
        return JobRunr.configure()
                .useStorageProvider(mongoDBStorageProvider)
                .withJobFilter(new MyJobClientFilter(), new MyJobServerFilter())
                .initialize();
    }

```
In application.yaml:
```

org.jobrunr.background-job-server.enabled: true
org.jobrunr.dashboard:
    enabled: true
    port: 8000
```
