### DISCUSSION TITLE
Jobs not getting deleted in JobRunr PRO even by setting custom delete policy

### DISCUSSION THREAD

**Discussion by kapilbablani** [jobrunr/jobrunr#625] [Q&A]
@rdehuyss Hey, I am using jobRunr PRO and set up the custom delete policy in spring boot application.yml file as follows-
```
org:
  jobrunr:
    background-job-server:
      delete-succeeded-jobs-after: 1
      permanently-delete-deleted-jobs-after: 2
```

Can you please guide if I am missing anything here ? I do the property getting set up properly in the mongo-db background_job_servers collection. But not marking deleted state neither deleting the entries.
