### DISCUSSION TITLE
MongoConfiguration error: uuidRepresentation has not been specified

### DISCUSSION THREAD

**Discussion by marque88** [jobrunr/jobrunr#872] [Q&A]
Hi I'm trying to configure MongoDB as storage.

I use quarkus extension and configure mongo client and all necessary, but when I start the project I receive this error:

```
2023-11-17 16:59:52,357 ERROR [org.job.ser.ServerZooKeeper] (backgroundjob-zookeeper-pool-8-thread-1) An unrecoverable error occurred. Shutting server down...: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.
```

I also tryed to add the relative `quarkus.mongodb.uuid-representation` property following the [quarkus mongo docs](https://quarkus.io/guides/mongodb#quarkus-mongodb_quarkus.mongodb.uuid-representation) but it is ignored.

Suggestions???

**Comment by rdehuyss** [comment]
I'm afraid I also would need to look into it and my time is currently limited for the OSS version.

**Comment by krickert** [comment]
This is a problem with the MongoDB client - somehow the code needs to specify the UUID representation.  It was introduced with mongodb 

Here's the full text of the error - which points how to fix this (I'm trying to see if this can be done w/o a code change)

```
Caused by: org.jobrunr.storage.StorageException: 
Since release 4.0.0 of the MongoDB Java Driver, the default BSON representation of java.util.UUID values has changed from JAVA_LEGACY to UNSPECIFIED.
Applications that store or retrieve UUID values must explicitly specify which representation to use, via the uuidRepresentation property of MongoClientSettings.
The good news is that JobRunr works both with the STANDARD as the JAVA_LEGACY uuidRepresentation. Please choose the one most appropriate for your application.
```

**Comment by krickert** [comment]
This configuration worked for me:

```
mongodb:
  servers.*.uuid-representation: java_legacy
  servers.*.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
consul.client.registration.enabled: true
jobrunr:
  background-job-server:
    enabled: true
  metrics:
    enabled: true #Micrometer integration - this was true in v5.
  dashboard:
    enabled: true
    port: 8000 #the port on which to start the dashboard
  database:
    skip-create: false
    type: mongodb # if you have multiple supported storage providers available in your application (e.g. an SQL DataSource and Elasticsearch), it allows to specify which database to choose. Valid values are 'sql', 'mongodb', 'redis-lettuce', 'redis-jedis' and 'elasticsearch'.
```
(Ignore the consul part - that's a whole other part of my app that I'm running)
