### ISSUE TITLE
[Feature] Added to Quarkus Extension Catalog

### ISSUE THREAD

**Issue by melloware** [jobrunr/jobrunr#1073]
I just added your extension with a PR to the Quarkus Extension Catalog: https://github.com/quarkusio/quarkus-extension-catalog/pull/104

This will make it appear to more users here: https://quarkus.io/extensions/ when they browse for extensions.

Howveer you might want to add an `icon-url` in your extension so it gets your custom logo.  For example see Mailpit example:
https://github.com/quarkiverse/quarkus-mailpit/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml

```yaml
icon-url: "https://raw.githubusercontent.com/quarkiverse/quarkus-mailpit/main/docs/modules/ROOT/assets/images/mailpit.svg"
sponsor: "XXX"
```

You might also want to add the Sponsor company in your extension as well showing its corporate backed.

**Comment by melloware** [comment]
OK its listed now: https://quarkus.io/extensions/org.jobrunr/quarkus-jobrunr/

I think you are missing some items which is why its showing up poorly you can update your extension.yaml to something like...

```yml
name: "JobRunr Extension"
description: "Integrates JobRunr, a distributed background job scheduler"
artifact: ${project.groupId}:${project.artifactId}:${project.version}
metadata:
  short-name: "jobrunr"
  keywords:
    - "jobrunr"
    - "scheduler"
    - "cron"
    - "distributed background jobs"
  guide: "https://www.jobrunr.io/en/documentation/configuration/quarkus/"
  icon-url: "https://user-images.githubusercontent.com/567842/80095933-1181c900-8569-11ea-85e7-14129b3f8142.png"
  sponsor: "Rosoco BV"
  categories:
    - "miscellaneous"
  status: "preview"
  extension-dependencies:
    - "io.quarkus:quarkus-arc"
    - "io.quarkus:quarkus-core"
```
