### ISSUE TITLE
[Feature] Redis Cluster support

### ISSUE THREAD

**Issue by JanecekPetr** [jobrunr/jobrunr#546]
### Is your feature request related to a problem? Please describe.
We're using [Redis Cluster](https://redis.io/docs/manual/scaling/) with a Spring Boot application, connecting via Lettuce. The JobRunr documentation says we're supposed to provide a `RedisClient` instance. However, for Redis Cluster this does not work as there's a separate `RedisClusterClient` class. When we try to provide the `RedisClient` instance, we get
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'jedisStorageProvider' threw exception; nested exception is org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	... ...
Caused by: java.lang.IllegalStateException: Error running database migration M001_LettuceRemoveJobStatsAndUseMetadata.class
	... 167 more
Caused by: io.lettuce.core.RedisCommandExecutionException: MOVED 8875 127.0.0.1:26380
	...
```

(Also note that this says _"method 'jedisStorageProvider' threw exception"_ even though this is Lettuce autoconfig. The method is misnamed.)

As a workaround we thought about using Jedis instead, however Jedis support is achieved via `JedisPool` where Jedis supports Redis Cluster via a `JedisCluster` class instead.

### Describe the solution you'd like
1. The `JobRunrLettuceStorageAutoConfiguration.jedisStorageProvider()` method should be renamed to `lettuceStorageProvider`.
2. Both `RedisClient` and `RedisClusterClient` should be acceptable dependencies.
3. (optional) for Jedis also `JedisCluster` should be acceptable
4. (optional) Overall the requirement of a specific client is ... annoying. It would be nice if the library would do with Spring's `RedisConnectionFactory` or `RedisTemplate` or some of its variants. Those are autoconfigured, do not need any additional beans or duplicate configuration. I've opened a separate ticket for this: #547.

### Describe alternatives you've considered
We considered Jedis. We also noted the warning
> Note: the Redis StorageProvider is still in BETA and not yet recommended for production use.
...and yet this is why we chose JobRunr over Quartz as for the time being that's the biggest feature for us.

### Additional context
The easiest way to set up a local Redis Cluster via docker compose is this:
```
  redis-cluster:
    image: grokzen/redis-cluster:latest
    ports:
      - "26379-26382:26379-26382"
    environment:
      - "INITIAL_PORT=26379"
      - "MASTERS=3"
      - "SLAVES_PER_MASTER=0"
      - "SENTINEL=false"
      - "REDIS_CLUSTER_IP=0.0.0.0"
      - "IP=0.0.0.0"
      - "BIND_ADDRESS=0.0.0.0"
```
then
```
spring:
  redis:
    cluster:
      nodes: "localhost:26379,localhost:26380,localhost:26381"
```
in your `application.yaml`. Of course this does not automatically work for `RedisClient` nor `RedisClusterClient`, so those need to be provided manually.
